configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true

# Restore NuGet packages before running MSBuild
before_build:
  - nuget restore

build:
  verbosity: minimal
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
# Symbol server died, had to comment out to allow the nuget push to go through
#  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
